"""
Global histogram builders for processed layer-cube datasets.

Design constraints
------------------
The exact histogram counts for ``np.histogram`` require fixed bin edges before
the first value is consumed. For processed datasets generated by this project,
those ranges can usually be inferred from pipeline reports because they already
store per-variable min/max normalization metadata. In that common case, the
tensor values are streamed exactly once.

If the processed dataset lacks usable min/max metadata (for example, outputs
saved with ``--no-normalize``), this module falls back to a second streaming
pass: pass 1 computes min/max only, pass 2 computes counts with fixed edges.
The fallback still avoids storing raw values and keeps memory usage bounded.
"""
from __future__ import annotations

import json
import math
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np


_REPORT_GLOB_PATTERNS: tuple[str, ...] = (
    "layer_cubes_report.json",
    "*_layer_cubes_report.json",
)


def _resolve_dataset_path(dataset: str | Path) -> Path:
    """Resolve a processed dataset path with a few project-aware fallbacks."""
    candidate = Path(dataset)
    if candidate.exists():
        return candidate

    processed_root = Path("data") / "processed"
    fallbacks = [
        processed_root / candidate,
        processed_root / "train" / candidate,
        processed_root / "test" / candidate,
    ]
    for fallback in fallbacks:
        if fallback.exists():
            return fallback

    if processed_root.exists():
        matches = [p for p in processed_root.rglob(candidate.name) if p.is_dir()]
        unique_matches: list[Path] = []
        seen: set[str] = set()
        for match in sorted(matches):
            key = str(match.resolve())
            if key in seen:
                continue
            seen.add(key)
            unique_matches.append(match)
        if len(unique_matches) == 1:
            return unique_matches[0]
        if len(unique_matches) > 1:
            options = ", ".join(str(path) for path in unique_matches[:5])
            raise ValueError(
                f"Dataset '{dataset}' es ambiguo dentro de data/processed. "
                f"Coincidencias: {options}"
            )

    raise FileNotFoundError(f"No se pudo resolver el dataset procesado: {dataset}")


def _resolve_report_output_dir(report_path: Path, report: Mapping[str, Any]) -> Path:
    output_dir = report.get("output_dir")
    if not output_dir:
        raise ValueError(f"El reporte no contiene 'output_dir': {report_path}")
    output_path = Path(str(output_dir))
    if output_path.is_absolute():
        return output_path
    # Reports often store paths relative to CWD (e.g. "data/processed/01/layer_cubes").
    # Try CWD first, then relative to the report file, then just the last segment as a
    # sibling of the report — handles renamed/moved directories without manual fixups.
    candidates = [
        (Path.cwd() / output_path).resolve(),
        (report_path.parent / output_path).resolve(),
        (report_path.parent / output_path.name).resolve(),
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]  # caller will get a clear error if it doesn't exist


def _discover_report_paths(
    dataset_path: Path,
    *,
    report_filename: str | None = None,
) -> list[Path]:
    if dataset_path.is_file():
        if not dataset_path.name.endswith("_report.json") and dataset_path.name != "layer_cubes_report.json":
            raise ValueError(f"Archivo no soportado como dataset: {dataset_path}")
        return [dataset_path]

    # When a specific filename is given, search only for that name so that
    # scanning data/processed/ for 'sf_vd' doesn't also pick up cohesion/afi
    # reports that share the same *_layer_cubes_report.json glob pattern.
    patterns = (report_filename,) if report_filename else _REPORT_GLOB_PATTERNS

    report_paths: list[Path] = []
    for pattern in patterns:
        report_paths.extend(dataset_path.rglob(pattern))

    unique_paths: list[Path] = []
    seen: set[str] = set()
    for path in sorted(report_paths):
        key = str(path.resolve())
        if key in seen:
            continue
        seen.add(key)
        unique_paths.append(path)
    return unique_paths


def _load_layer_reports(
    dataset: str | Path,
    *,
    report_filename: str | None = None,
) -> list[dict[str, Any]]:
    dataset_path = _resolve_dataset_path(dataset)
    report_paths = _discover_report_paths(dataset_path, report_filename=report_filename)
    if not report_paths:
        raise RuntimeError(
            f"No se encontraron reportes de capas dentro de {dataset_path}. "
            "Se esperaba al menos un 'layer_cubes_report.json' o '*_layer_cubes_report.json'."
        )

    reports: list[dict[str, Any]] = []
    for report_path in report_paths:
        report = json.loads(report_path.read_text(encoding="utf-8"))
        output_dir = _resolve_report_output_dir(report_path, report)
        variable_order = [str(v) for v in report.get("variable_order", [])]
        if not variable_order:
            raise ValueError(f"El reporte no define 'variable_order': {report_path}")
        reports.append(
            {
                "report_path": report_path,
                "output_dir": output_dir,
                "variable_order": variable_order,
                "normalization": report.get("normalization") or {},
            }
        )
    return reports


def _list_layer_files(dataset: str | Path) -> tuple[list[Path], Path]:
    """
    List all layer cube files associated with a processed dataset root.

    Returns
    -------
    files, dataset_root
        ``files`` contains every ``layer_cube_k*.pt/.npz`` found through the
        pipeline reports below ``dataset``. The second item is the resolved
        dataset root used for discovery.
    """
    dataset_path = _resolve_dataset_path(dataset)
    reports = _load_layer_reports(dataset_path)
    files: list[Path] = []
    for entry in reports:
        output_dir = Path(entry["output_dir"])
        files.extend(sorted(output_dir.glob("layer_cube_k*.pt")))
        files.extend(sorted(output_dir.glob("layer_cube_k*.npz")))

    unique_files: list[Path] = []
    seen: set[str] = set()
    for file_path in files:
        key = str(file_path.resolve())
        if key in seen:
            continue
        seen.add(key)
        unique_files.append(file_path)

    if not unique_files:
        raise RuntimeError(
            f"No hay archivos layer_cube_k*.pt/.npz accesibles bajo {dataset_path}."
        )
    return unique_files, dataset_path


def load_layer_cube(file_path: Path) -> dict[str, Any]:
    """Load one processed layer cube saved either as ``.pt`` or ``.npz``."""
    if file_path.suffix == ".pt":
        try:
            import torch
        except ModuleNotFoundError as exc:
            raise RuntimeError("PyTorch es requerido para leer archivos .pt.") from exc

        payload = torch.load(file_path, map_location="cpu")
        cube = payload["cube"]
        if hasattr(cube, "detach"):
            cube = cube.detach().cpu().numpy()
        return {
            "cube": np.asarray(cube),
            "time_ids": list(payload.get("time_ids", [])),
            "time_ids_days": list(payload.get("time_ids_days", [])),
            "time_unit": str(payload.get("time_unit", "days")),
            "variables": [str(v) for v in payload.get("variables", [])],
            "layer_k": int(payload.get("layer_k", -1)),
            "normalization": payload.get("normalization"),
        }

    if file_path.suffix == ".npz":
        with np.load(file_path, allow_pickle=True) as payload:
            variables = [str(v) for v in np.asarray(payload["variables"]).tolist()]
            time_ids = [int(v) for v in np.asarray(payload["time_ids"]).tolist()]
            time_ids_days = [int(v) for v in np.asarray(payload["time_ids_days"]).tolist()]
            time_unit = str(np.asarray(payload["time_unit"]).reshape(-1)[0])
            normalization = {
                "method": str(np.asarray(payload["normalization_method"]).reshape(-1)[0]),
                "applied": bool(int(np.asarray(payload["normalization_applied"]).reshape(-1)[0])),
            }
            return {
                "cube": np.asarray(payload["cube"]),
                "time_ids": time_ids,
                "time_ids_days": time_ids_days,
                "time_unit": time_unit,
                "variables": variables,
                "layer_k": int(np.asarray(payload["layer_k"]).reshape(-1)[0]),
                "normalization": normalization,
            }

    raise ValueError(f"Formato de archivo no soportado: {file_path}")


def _normalize_variable_filter(variables: Sequence[str] | None) -> set[str] | None:
    if variables is None:
        return None
    normalized = {str(variable).strip().upper() for variable in variables if str(variable).strip()}
    return normalized or None


def _as_explicit_edges(
    bins: int | Sequence[float] | Mapping[str, Sequence[float]],
    var_name: str,
) -> np.ndarray | None:
    if isinstance(bins, Mapping):
        if var_name not in bins:
            return None
        edges = np.asarray(list(bins[var_name]), dtype=np.float64)
        return edges
    if isinstance(bins, (str, bytes)):
        raise TypeError("El argumento 'bins' no puede ser string.")
    if np.isscalar(bins):
        return None
    edges = np.asarray(list(bins), dtype=np.float64)
    return edges


def _validate_edges(edges: np.ndarray, *, var_name: str) -> np.ndarray:
    if edges.ndim != 1 or edges.size < 2:
        raise ValueError(f"Los bins de '{var_name}' deben ser un vector 1D con al menos 2 bordes.")
    deltas = np.diff(edges)
    if np.any(deltas <= 0):
        raise ValueError(f"Los bins de '{var_name}' deben ser estrictamente crecientes.")
    return edges


def _compute_edges_from_range(
    var_name: str,
    *,
    bins: int,
    value_min: float,
    value_max: float,
    log_bins: bool,
) -> np.ndarray:
    if bins <= 0:
        raise ValueError("'bins' debe ser un entero positivo.")
    if not np.isfinite(value_min) or not np.isfinite(value_max):
        raise ValueError(f"Rango inválido para '{var_name}': min={value_min}, max={value_max}")

    if value_min == value_max:
        if value_min == 0.0:
            value_min, value_max = -0.5, 0.5
        else:
            delta = abs(value_min) * 0.5 or 0.5
            value_min -= delta
            value_max += delta

    if log_bins:
        if value_min <= 0.0:
            raise ValueError(
                f"No se pueden construir bins logarítmicos para '{var_name}' con min={value_min}. "
                "Todos los valores deben ser > 0."
            )
        return np.logspace(np.log10(value_min), np.log10(value_max), bins + 1, dtype=np.float64)

    return np.linspace(value_min, value_max, bins + 1, dtype=np.float64)


def _infer_ranges_from_reports(
    reports: Sequence[Mapping[str, Any]],
    *,
    selected_variables: set[str] | None,
) -> dict[str, tuple[float, float]]:
    ranges: dict[str, tuple[float, float]] = {}
    for entry in reports:
        normalization = entry.get("normalization") or {}
        per_variable = normalization.get("per_variable") or {}
        for var_name in entry.get("variable_order", []):
            key = str(var_name).upper()
            if selected_variables is not None and key not in selected_variables:
                continue
            stats = per_variable.get(var_name)
            if not stats:
                continue
            try:
                vmin = float(stats["min"])
                vmax = float(stats["max"])
            except (KeyError, TypeError, ValueError):
                continue
            current = ranges.get(key)
            if current is None:
                ranges[key] = (vmin, vmax)
            else:
                ranges[key] = (min(current[0], vmin), max(current[1], vmax))
    return ranges


def _build_edges_from_reports(
    reports: Sequence[Mapping[str, Any]],
    *,
    bins: int | Sequence[float] | Mapping[str, Sequence[float]],
    selected_variables: set[str] | None,
    log_bins: bool,
) -> tuple[dict[str, np.ndarray], bool]:
    edges_by_var: dict[str, np.ndarray] = {}
    needs_data_ranges = False
    inferred_ranges = _infer_ranges_from_reports(reports, selected_variables=selected_variables)

    all_variables: list[str] = []
    for entry in reports:
        for var_name in entry["variable_order"]:
            key = str(var_name).upper()
            if selected_variables is not None and key not in selected_variables:
                continue
            if key not in all_variables:
                all_variables.append(key)

    for var_name in all_variables:
        explicit_edges = _as_explicit_edges(bins, var_name)
        if explicit_edges is not None:
            edges_by_var[var_name] = _validate_edges(explicit_edges, var_name=var_name)
            continue

        if not np.isscalar(bins):
            raise ValueError(
                "Si 'bins' no es entero, debe ser una secuencia de bordes compartidos o "
                "un mapping {variable: bordes}."
            )

        range_pair = inferred_ranges.get(var_name)
        if range_pair is None:
            needs_data_ranges = True
            continue
        edges_by_var[var_name] = _compute_edges_from_range(
            var_name,
            bins=int(bins),
            value_min=range_pair[0],
            value_max=range_pair[1],
            log_bins=log_bins,
        )
    return edges_by_var, needs_data_ranges


def _update_streaming_stats(
    state: dict[str, dict[str, Any]],
    var_name: str,
    values: np.ndarray,
    *,
    edges: np.ndarray | None,
) -> None:
    bucket = state.setdefault(
        var_name,
        {
            "counts": None if edges is None else np.zeros(edges.size - 1, dtype=np.int64),
            "min": math.inf,
            "max": -math.inf,
            "sum": 0.0,
            "sum_sq": 0.0,
            "n": 0,
        },
    )

    if values.size == 0:
        return

    bucket["min"] = min(bucket["min"], float(values.min()))
    bucket["max"] = max(bucket["max"], float(values.max()))
    bucket["sum"] += float(values.sum(dtype=np.float64))
    bucket["sum_sq"] += float(np.square(values, dtype=np.float64).sum(dtype=np.float64))
    bucket["n"] += int(values.size)

    if edges is not None:
        if bucket["counts"] is None:
            bucket["counts"] = np.zeros(edges.size - 1, dtype=np.int64)
        bucket["counts"] += np.histogram(values, bins=edges)[0].astype(np.int64, copy=False)


def _stream_dataset(
    files: Iterable[Path],
    *,
    edges_by_var: Mapping[str, np.ndarray] | None,
    selected_variables: set[str] | None,
) -> dict[str, dict[str, Any]]:
    state: dict[str, dict[str, Any]] = {}
    for file_path in files:
        payload = load_layer_cube(file_path)
        cube = np.asarray(payload["cube"])
        variables = [str(v).upper() for v in payload.get("variables", [])]
        if cube.ndim != 4:
            raise ValueError(
                f"Se esperaba un cubo 4D (V, T, J, I) en {file_path}, recibido shape={cube.shape}."
            )
        if cube.shape[0] != len(variables):
            raise ValueError(
                f"Cantidad de variables inconsistente en {file_path}: "
                f"shape[0]={cube.shape[0]} vs variables={variables}"
            )

        for var_idx, var_name in enumerate(variables):
            if selected_variables is not None and var_name not in selected_variables:
                continue
            values = np.asarray(cube[var_idx], dtype=np.float64)
            finite_values = values[np.isfinite(values)]
            if finite_values.size == 0:
                continue
            edges = None if edges_by_var is None else edges_by_var.get(var_name)
            _update_streaming_stats(state, var_name, finite_values, edges=edges)
    return state


def _compute_edges_from_state(
    state: Mapping[str, Mapping[str, Any]],
    *,
    bins: int,
    log_bins: bool,
) -> dict[str, np.ndarray]:
    edges_by_var: dict[str, np.ndarray] = {}
    for var_name, stats in state.items():
        if int(stats["n"]) <= 0:
            continue
        edges_by_var[var_name] = _compute_edges_from_range(
            var_name,
            bins=bins,
            value_min=float(stats["min"]),
            value_max=float(stats["max"]),
            log_bins=log_bins,
        )
    return edges_by_var


def _approximate_percentile_from_histogram(
    edges: np.ndarray,
    counts: np.ndarray,
    percentile: float,
) -> float | None:
    total = int(counts.sum())
    if total <= 0:
        return None
    if percentile <= 0.0:
        return float(edges[0])
    if percentile >= 100.0:
        return float(edges[-1])

    target = percentile / 100.0 * total
    cumulative = np.cumsum(counts, dtype=np.int64)
    idx = int(np.searchsorted(cumulative, target, side="left"))
    idx = min(max(idx, 0), counts.size - 1)
    left = float(edges[idx])
    right = float(edges[idx + 1])
    prev_cum = int(cumulative[idx - 1]) if idx > 0 else 0
    bin_count = int(counts[idx])
    if bin_count <= 0:
        return left
    fraction = (target - prev_cum) / bin_count
    fraction = min(max(float(fraction), 0.0), 1.0)
    return left + (right - left) * fraction


def _finalize_histogram_payload(
    state: Mapping[str, Mapping[str, Any]],
    edges_by_var: Mapping[str, np.ndarray],
) -> dict[str, dict[str, Any]]:
    payload: dict[str, dict[str, Any]] = {}
    for var_name, stats in state.items():
        n = int(stats["n"])
        if n <= 0:
            continue
        counts = np.asarray(stats["counts"], dtype=np.int64)
        edges = np.asarray(edges_by_var[var_name], dtype=np.float64)
        mean = float(stats["sum"] / n)
        variance = max(float(stats["sum_sq"] / n) - (mean * mean), 0.0)
        payload[var_name] = {
            "bins": [float(v) for v in edges.tolist()],
            "counts": [int(v) for v in counts.tolist()],
            "min": float(stats["min"]),
            "max": float(stats["max"]),
            "mean": mean,
            "std": float(math.sqrt(variance)),
            "n": n,
            "p5": _approximate_percentile_from_histogram(edges, counts, 5.0),
            "p50": _approximate_percentile_from_histogram(edges, counts, 50.0),
            "p95": _approximate_percentile_from_histogram(edges, counts, 95.0),
        }
    if not payload:
        raise RuntimeError("No se encontraron valores finitos para construir histogramas.")
    return payload


def _files_from_reports(reports: Sequence[Mapping[str, Any]]) -> list[Path]:
    """Collect all layer-cube files from an already-loaded list of report dicts."""
    files: list[Path] = []
    for entry in reports:
        output_dir = Path(entry["output_dir"])
        files.extend(sorted(output_dir.glob("layer_cube_k*.pt")))
        files.extend(sorted(output_dir.glob("layer_cube_k*.npz")))
    unique: list[Path] = []
    seen: set[str] = set()
    for fp in files:
        key = str(fp.resolve())
        if key not in seen:
            seen.add(key)
            unique.append(fp)
    if not unique:
        raise RuntimeError("No hay archivos layer_cube_k*.pt/.npz accesibles en los reportes.")
    return unique


def construir_histogramas_globales_por_capas(
    dataset: str | Path,
    bins: int | Sequence[float] | Mapping[str, Sequence[float]],
    output_path: str | Path,
    *,
    variables: Sequence[str] | None = None,
    log_bins: bool = False,
    strict_single_pass: bool = False,
    report_filename: str | None = None,
) -> dict[str, dict[str, Any]]:
    """
    Build global histograms per variable from processed layer cubes.

    Parameters
    ----------
    dataset:
        Root directory under ``data/processed`` or an explicit processed path.
        The function discovers all layer-cube reports recursively and streams the
        corresponding ``layer_cube_k*.pt/.npz`` files.
    bins:
        Either:
        - ``int``: number of equally spaced bins per variable.
        - ``Sequence[float]``: shared explicit edges for every variable.
        - ``Mapping[str, Sequence[float]]``: explicit edges per variable.
    output_path:
        Destination JSON file.
    variables:
        Optional subset of variables to process.
    log_bins:
        Use logarithmic edges when ``bins`` is an integer.
    strict_single_pass:
        If ``True``, abort when exact edges cannot be derived from metadata
        without a full first pass over tensor values.
    report_filename:
        Restrict discovery to this exact report filename (e.g.
        ``'layer_cubes_report.json'``). Required when *dataset* is a root
        directory that contains reports for multiple variable groups, so that
        only the intended group is included.
    """
    reports = _load_layer_reports(dataset, report_filename=report_filename)
    files = _files_from_reports(reports)
    selected_variables = _normalize_variable_filter(variables)

    edges_by_var, needs_data_ranges = _build_edges_from_reports(
        reports,
        bins=bins,
        selected_variables=selected_variables,
        log_bins=log_bins,
    )

    if needs_data_ranges:
        if strict_single_pass:
            raise RuntimeError(
                "No fue posible inferir todos los rangos desde metadata. "
                "Para un histograma exacto de una sola pasada, proporciona bins explícitos "
                "o procesa artefactos con min/max disponibles en los reportes."
            )
        if not np.isscalar(bins):
            raise RuntimeError(
                "Faltan bins explícitos para al menos una variable y no se puede "
                "hacer fallback con bins no escalares."
            )
        range_state = _stream_dataset(
            files,
            edges_by_var=None,
            selected_variables=selected_variables,
        )
        edges_by_var = _compute_edges_from_state(
            range_state,
            bins=int(bins),
            log_bins=log_bins,
        )

    histogram_state = _stream_dataset(
        files,
        edges_by_var=edges_by_var,
        selected_variables=selected_variables,
    )
    payload = _finalize_histogram_payload(histogram_state, edges_by_var)

    now = datetime.now().isoformat(timespec="seconds")
    payload["_meta"] = {
        "processed_report_paths": [str(r["report_path"].resolve()) for r in reports],
        "total_simulations": len(reports),
        "built_at": now,
        "last_updated": now,
    }

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def _variable_keys(histogram_payload: Mapping[str, Any]) -> list[str]:
    """Return only the variable keys, excluding reserved metadata keys."""
    return [k for k in histogram_payload if k != "_meta"]


def _merge_variable_into_payload(
    existing_var: dict[str, Any],
    new_stats: dict[str, Any],
    edges: np.ndarray,
) -> dict[str, Any]:
    """
    Merge streaming stats from *new_stats* into *existing_var* (from a saved JSON).

    Counts are summed bin-by-bin (bin edges are guaranteed identical).
    Mean and std are recombined with the parallel/chunked variance formula
    so no raw values need to be stored or reloaded.
    """
    n1 = int(existing_var["n"])
    n2 = int(new_stats["n"])
    if n2 <= 0:
        return existing_var

    n_total = n1 + n2
    mean1 = float(existing_var["mean"])
    mean2 = float(new_stats["sum"]) / n2
    mean_total = (mean1 * n1 + mean2 * n2) / n_total

    var1 = float(existing_var["std"]) ** 2
    var2 = max(float(new_stats["sum_sq"]) / n2 - mean2 ** 2, 0.0)
    var_total = (
        n1 * (var1 + (mean1 - mean_total) ** 2)
        + n2 * (var2 + (mean2 - mean_total) ** 2)
    ) / n_total

    counts_total = (
        np.asarray(existing_var["counts"], dtype=np.int64)
        + np.asarray(new_stats["counts"], dtype=np.int64)
    )

    return {
        "bins": existing_var["bins"],
        "counts": [int(v) for v in counts_total.tolist()],
        "min": min(float(existing_var["min"]), float(new_stats["min"])),
        "max": max(float(existing_var["max"]), float(new_stats["max"])),
        "mean": mean_total,
        "std": math.sqrt(max(var_total, 0.0)),
        "n": n_total,
        "p5": _approximate_percentile_from_histogram(edges, counts_total, 5.0),
        "p50": _approximate_percentile_from_histogram(edges, counts_total, 50.0),
        "p95": _approximate_percentile_from_histogram(edges, counts_total, 95.0),
    }


def actualizar_histogramas_globales(
    json_path: str | Path,
    dataset: str | Path,
    *,
    variables: Sequence[str] | None = None,
    report_filename: str | None = None,
) -> dict[str, dict[str, Any]] | None:
    """
    Incrementally update an existing histogram JSON with new simulations.

    Reads ``_meta.processed_report_paths`` from the JSON, discovers all current
    reports for *dataset*, and processes only the ones not yet registered.
    Bin edges stored in the JSON are reused as-is — no need to re-read any
    previously processed files.

    Returns the updated payload, or ``None`` if nothing new was found.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        raise FileNotFoundError(
            f"JSON no encontrado: {json_path}. "
            "Ejecuta construir_histogramas_globales_por_capas() primero."
        )

    existing_payload: dict[str, Any] = json.loads(json_path.read_text(encoding="utf-8"))
    meta: dict[str, Any] = existing_payload.get("_meta") or {}
    already_processed: set[str] = set(meta.get("processed_report_paths") or [])

    dataset_path = _resolve_dataset_path(dataset)
    all_report_paths = _discover_report_paths(dataset_path, report_filename=report_filename)
    new_report_paths = [
        rp for rp in all_report_paths
        if str(rp.resolve()) not in already_processed
    ]

    if not new_report_paths:
        return None

    print(
        f"  {len(new_report_paths)} simulaciones nuevas "
        f"(de {len(all_report_paths)} totales) en {dataset_path.name}"
    )

    # Collect layer-cube files for the new reports only
    new_files: list[Path] = []
    for rp in new_report_paths:
        report = json.loads(rp.read_text(encoding="utf-8"))
        output_dir = _resolve_report_output_dir(rp, report)
        new_files.extend(sorted(output_dir.glob("layer_cube_k*.pt")))
        new_files.extend(sorted(output_dir.glob("layer_cube_k*.npz")))

    # Deduplicate
    seen: set[str] = set()
    unique_new_files: list[Path] = []
    for fp in new_files:
        key = str(fp.resolve())
        if key not in seen:
            seen.add(key)
            unique_new_files.append(fp)

    if not unique_new_files:
        raise RuntimeError(
            "Se encontraron reportes nuevos pero ningún archivo layer_cube_k*.pt/.npz."
        )

    # Reuse existing bin edges — no re-read of old data needed
    selected_variables = _normalize_variable_filter(variables)
    edges_by_var: dict[str, np.ndarray] = {}
    for var_name in _variable_keys(existing_payload):
        if selected_variables is not None and var_name not in selected_variables:
            continue
        edges_by_var[var_name] = np.asarray(
            existing_payload[var_name]["bins"], dtype=np.float64
        )

    new_state = _stream_dataset(
        unique_new_files,
        edges_by_var=edges_by_var,
        selected_variables=selected_variables,
    )

    for var_name, new_var_stats in new_state.items():
        if var_name not in existing_payload:
            continue
        existing_payload[var_name] = _merge_variable_into_payload(
            existing_payload[var_name],
            new_var_stats,
            edges_by_var[var_name],
        )

    now = datetime.now().isoformat(timespec="seconds")
    new_processed_paths = list(already_processed) + [
        str(rp.resolve()) for rp in new_report_paths
    ]
    existing_payload["_meta"] = {
        **meta,
        "processed_report_paths": new_processed_paths,
        "total_simulations": len(new_processed_paths),
        "last_updated": now,
    }

    json_path.write_text(json.dumps(existing_payload, indent=2), encoding="utf-8")
    return existing_payload


def _resolve_histogram_variable_name(
    histogram_payload: Mapping[str, Any],
    variable: str | int | None,
) -> str:
    keys = _variable_keys(histogram_payload)
    if not keys:
        raise ValueError("El JSON no contiene histogramas.")
    if variable is None:
        if len(keys) != 1:
            raise ValueError(
                f"Debes indicar una variable. Variables disponibles: {keys}"
            )
        return keys[0]
    if isinstance(variable, int):
        if not (0 <= variable < len(keys)):
            raise ValueError(f"Índice de variable fuera de rango: {variable}")
        return keys[variable]
    variable_key = str(variable).strip().upper()
    for key in keys:
        if key.upper() == variable_key:
            return key
    raise KeyError(f"Variable no encontrada en el JSON: {variable}. Disponibles: {keys}")


def graficar_histograma_global(
    json_path: str | Path,
    variable: str | int | None = None,
    *,
    log_y: bool = False,
    ax: Any = None,
    figsize: tuple[float, float] = (8.0, 4.0),
    color: str = "#2f6db3",
) -> Any:
    """
    Plot a global histogram directly from the lightweight JSON artifact.

    Returns the Matplotlib axis used for plotting so callers can compose it
    into larger figures when needed.
    """
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib es requerido para graficar histogramas.") from exc

    payload = json.loads(Path(json_path).read_text(encoding="utf-8"))
    var_name = _resolve_histogram_variable_name(payload, variable)
    stats = payload[var_name]
    edges = np.asarray(stats["bins"], dtype=np.float64)
    counts = np.asarray(stats["counts"], dtype=np.int64)

    if counts.size + 1 != edges.size:
        raise ValueError(
            f"JSON corrupto para '{var_name}': len(bins)={edges.size}, len(counts)={counts.size}"
        )

    created_axis = ax is None
    if created_axis:
        _, ax = plt.subplots(figsize=figsize)

    widths = np.diff(edges)
    ax.bar(
        edges[:-1],
        counts,
        width=widths,
        align="edge",
        color=color,
        edgecolor="white",
        linewidth=0.6,
    )
    ax.set_title(f"Histograma global | {var_name}")
    ax.set_xlabel("Valor")
    ax.set_ylabel("Frecuencia")
    if log_y:
        ax.set_yscale("log")
    ax.grid(True, axis="y", alpha=0.25)

    subtitle = (
        f"n={stats['n']} | min={stats['min']:.6g} | max={stats['max']:.6g} | "
        f"mean={stats['mean']:.6g} | std={stats['std']:.6g}"
    )
    ax.text(0.01, 0.98, subtitle, transform=ax.transAxes, va="top", ha="left", fontsize=9)

    if created_axis:
        plt.tight_layout()
        plt.show()
    return ax


def graficar_todas_variables(
    json_path: str | Path,
    *,
    log_y: bool = False,
    figsize_per_var: tuple[float, float] = (9.0, 3.5),
    color: str = "#2f6db3",
) -> None:
    """
    Plot every variable stored in a histogram JSON as stacked subplots.

    Useful for a quick overview of a full dataset without having to call
    ``graficar_histograma_global`` once per variable.
    """
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib es requerido para graficar histogramas.") from exc

    payload = json.loads(Path(json_path).read_text(encoding="utf-8"))
    keys = _variable_keys(payload)
    if not keys:
        raise ValueError("El JSON no contiene histogramas.")

    n = len(keys)
    _, axes = plt.subplots(
        n, 1,
        figsize=(figsize_per_var[0], figsize_per_var[1] * n),
        squeeze=False,
    )
    for ax, var_name in zip(axes[:, 0], keys):
        graficar_histograma_global(json_path, var_name, log_y=log_y, ax=ax, color=color)
    plt.tight_layout()
    plt.show()


__all__ = [
    "load_layer_cube",
    "_list_layer_files",
    "construir_histogramas_globales_por_capas",
    "actualizar_histogramas_globales",
    "graficar_histograma_global",
    "graficar_todas_variables",
]
